module.exports = {
	base: "https://kyra.tk",
	fun: "https://kyra.tk/v2/fun/",
	endpoints: {
		ass: "https://kyra.tk/v2/nsfw/img?end=ass&apikey=",
		assgif: "https://kyra.tk/v2/nsfw/img?end=assgif&apikey=",
		bbw: "https://kyra.tk/v2/nsfw/img?end=bbw&apikey=",
		bdsm: "https://kyra.tk/v2/nsfw/img?end=bdsm&apikey=",
		blow: "https://kyra.tk/v2/nsfw/img?end=blow&apikey=",
		boobs: "https://kyra.tk/v2/nsfw/img?end=boobs&apikey=",
		feet: "https://kyra.tk/v2/nsfw/img?end=feet&apikey=",
		furfuta: "https://kyra.tk/v2/nsfw/img?end=furfuta&apikey=",
		athighs: "https://kyra.tk/v2/nsfw/img?end=athighs&apikey=",
		furgif: "https://kyra.tk/v2/nsfw/img?end=furgif&apikey=",
		futa: "https://kyra.tk/v2/nsfw/img?end=futa&apikey=",
		gifs: "https://kyra.tk/v2/nsfw/img?end=gifs&apikey=",
		hass: "https://kyra.tk/v2/nsfw/img?end=hass&apikey=",
		hboobs: "https://kyra.tk/v2/nsfw/img?end=hboobs&apikey=",
		hentai: "https://kyra.tk/v2/nsfw/img?end=hentai&apikey=",
		kink: "https://kyra.tk/v2/nsfw/img?end=kink&apikey=",
		latex: "https://kyra.tk/v2/nsfw/img?end=latex&apikey=",
		milk: "https://kyra.tk/v2/nsfw/img?end=milk&apikey=",
		pantsu: "https://kyra.tk/v2/nsfw/img?end=pantsu&apikey=",
		random: "https://kyra.tk/v2/nsfw/img?end=random&apikey=",
		sex: "https://kyra.tk/v2/nsfw/img?end=sex&apikey=",
		slime: "https://kyra.tk/v2/nsfw/img?end=slime&apikey=",
		thighs: "https://kyra.tk/v2/nsfw/img?end=thighs&apikey=",
		trap: "https://kyra.tk/v2/nsfw/img?end=trap&apikey=",
		yuri: "https://kyra.tk/v2/nsfw/img?end=yuri&apikey=",
		irlfemb: "https://kyra.tk/v2/nsfw/img?end=irlfemb&apikey="
	}
}
