module.exports = {
	base: "https://akira.gay/api/v1/nsfw/",
	fun: "https://akira.gay/api/v1/fun/",
	endpoints: {
		ass: "https://akira.gay/api/v1/nsfw/ass",
		sex: "https://akira.gay/api/v1/nsfw/sex",
		futa: "https://akira.gay/api/v1/nsfw/futa",
		furgif: "https://akira.gay/api/v1/nsfw/furgif",
		furfuta: "https://akira.gay/api/v1/nsfw/furfuta",
		boobs: "https://akira.gay/api/v1/nsfw/boobs",
		athighs: "https://akira.gay/api/v1/nsfw/athighs",
		feet: "https://akira.gay/api/v1/nsfw/feet",
		gifs: "https://akira.gay/api/v1/nsfw/gifs",
		hboobs: "https://akira.gay/api/v1/nsfw/hboobs",
		hentai: "https://akira.gay/api/v1/nsfw/hentai",
		kink: "https://akira.gay/api/v1/nsfw/kink",
		thighs: "https://akira.gay/api/v1/nsfw/thighs",
		yuri: "https://akira.gay/api/v1/nsfw/yuri",
		milk: "https://akira.gay/api/v1/nsfw/milk",
		slime: "https://akira.gay/api/v1/nsfw/slime",
		trap: "https://akira.gay/api/v1/nsfw/trap",
		kiss: "https://akira.gay/api/v1/sfw/kiss",
		pantsu: "https://akira.gay/api/v1/nsfw/pantsu",
		blow: "https://akira.gay/api/v1/nsfw/blow",
		chat: "https://akira.gay/api/v1/fun/chat",
		godSearch: "https://akira.gay/api/v1/image/god?search=",
		welcome: "https://akira.gay/api/v1/image/welcome?",
		onlyImage: "https://akira.gay/api/v1/image/only?message="
	}
}